#!/bin/bash

# check OS, establish filePaths
    OS=$(uname)
    userName=$(whoami)
    if [[ $OS == "Darwin" ]]; then
        scriptPath="/Users/$userName/Documents/Github/IG_Scripts/"
    elif [[ $OS == "Linux" ]]; then
        scriptPath="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/"
    else
        echo "Not able to detect Operating System"
        exit
    fi
#

addChecker () {
    fileRes=$(ffprobe -v quiet -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$1")
    if [[ "$fileRes" == "1440x1080" ]]; then
        ch="${scriptPath}assets/checkers1440.jpg"
    elif [[ "$fileRes" == "1920x1080" ]]; then
        ch="${scriptPath}assets/checkers1920.jpg"
    elif [[ "$fileRes" == "2160x1215" ]]; then
        ch="${scriptPath}assets/checkers2160.jpg"
    elif [[ "$fileRes" == "2880x1620" ]]; then
        ch="${scriptPath}assets/checkers2880.jpg"
    elif [[ "$fileRes"s == "3840x2160" ]]; then
        ch="${scriptPath}assets/checkers3840.jpg"
    else
        echo "Could not find checker image that matches size"
        exit
    fi

    magick "$ch" "$1" -gravity center -composite "${i%".png"}_CH.jpg"
}

for i in *.png; do
    addChecker "$i"
done