#!/bin/bash

scriptPath="$1"

cd "./02_Title"
for i in *; do
    cd "./$i/_Images"
    ${scriptPath}checkImages
    cd ..
    cd "./_Motions"
    ${scriptPath}checkMotions
    cd ../../
done
cd ..

cd "./03_Social"
for i in *; do
    cd "./$i/_Images"
    ${scriptPath}checkImages
    cd ..
    cd "./_Motions"
    ${scriptPath}checkMotions
    cd ../../
done
cd ..

cd "./04_Worship Background/_Motions"
${scriptPath}checkMotions
cd ../../

cd "./05_Countdown & Trivia/_Motions"
${scriptPath}checkMotions
cd ../../

cd "./06_Bumper/_Motions"
${scriptPath}checkMotions
cd ../../