#!/bin/bash

suffixHD="_HD"
suffixSD="_SD"
suffixLS="_LS"
suffixPR="_PR"
suffixSQ="_SQ"

prefixUW="UW_"

resHD="1920x1080"
resSD="1440x1080"
resUWHD="3840x720"
resUWSD="1920x480"
resLS="1280x720"
resPR="1080x1920"
resSQ="1080x1080"

for i in *.mov; do 
    fileRes=$(ffprobe -v quiet -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$i")
    if [[ "$i" == *"$suffixHD"* ]] || [[ "$i" == *"$suffixSD"* ]] || [[ "$i" == *"$suffixLS"* ]] || [[ "$i" == *"$suffixPR"* ]] || [[ "$i" == *"$suffixSQ"* ]] || [[ "$i" == "*.mov" ]]; then
        check="Success"
    else
        echo "  Incorrect Suffix for: $i"
    fi
    if ([[ "$fileRes" == "$resHD" ]] && [[ "$i" == *"$suffixHD"* ]]) || ([[ "$fileRes" == "$resSD" ]] && [[ "$i" == *"$suffixSD"* ]]) || ([[ "$fileRes" == "$resUWHD" ]] && [[ "$i" == *"$suffixHD"* ]] && [[ "$i" == *"$prefixUW"* ]]) || ([[ "$fileRes" == "$resUWSD" ]] && [[ "$i" == *"$suffixSD"* ]] && [[ "$i" == *"$prefixUW"* ]]) || ([[ "$fileRes" == "$resLS" ]] && [[ "$i" == *"$suffixLS"* ]]) || ([[ "$fileRes" == "$resPR" ]] && [[ "$i" == *"$suffixPR"* ]]) || ([[ "$fileRes" == "$resSQ" ]] && [[ "$i" == *"$suffixSQ"* ]]) || [[ "$i" == "*.mov" ]]; then
        check="Success"
    else
        echo "  Incorrect Resolution for: $i"
        echo "    Resolution Found: $fileRes"
    fi
done