#!/bin/bash

filter1="$1"
filter2="$2"

mkdir -p "_Originals"

for i in *.mov; do
    if ([[ "$i" == *"$filter1"* ]] || [[ "$i" == *"$filter2"* ]]) && [[ "$i" != "*.mov" ]]; then
        fileName=${i%".mov"}.mp4
        ffmpeg -loglevel quiet -n -i "$i" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$fileName"
        mv -f "$i" "./Originals/"
    fi
done