#!/bin/bash

echo "  Copying Photoshop Projects to Uploads"

newPath="$1"
filePrefix="$2"

for i in *.psd *.zip; do
    newName="${newPath}${filePrefix}_$i"

    if [[ "$i" == *".psd"* ]]; then
        cp -p "Copying " "$i" "$newName"
    elif [[ "$i" == *".zip"* ]] && [[ "$i" != *"*.zip"* ]]; then
        mv -p "Moving " "$i" "$newName"
    fi
done