#!/bin/bash

echo "  Copying Motions to Uploads"

newPath="$1"
filePrefix="$2"

for i in *.mov *.jpg *.mp4; do
    if ([[ "$i" == *"Countdown_"* ]] && [[ "$i" == *".mov"* ]]) || ([[ "$i" == *"Trivia_"* ]] && [[ "$i" == *".mov"* ]]) || [[ "$i" == *"*.mp4"* ]] || [[ "$i" == *"*.mov"* ]] || [[ "$i" == *"*.jpg"* ]]; then
        dontCopy="TRUE"
    else
        cp -i "$i" "${newPath}${filePrefix%"/"}_$i"
    fi
done