#!/bin/bash

uploadsPath="$1"
filePrefix="$3"
lookName="$4"
projName="$5"

for i in *.mov *.jpg *.mp4; do
    if [[ "$oneLook" == "FALSE" ]]; then 
        motionPath="${uploadsPath}${projName}_UPLOADS/${lookName}/Motions/${filePrefix}_$i"
    elif [[ "$oneLook" == "TRUE" ]]; then
        motionPath="${uploadsPath}${projName}_UPLOADS/Motions/${filePrefix}_$i"
    fi

    if ([[ "$i" == *"Countdown_"* ]] && [[ "$i" == *".mov"* ]]) || ([[ "$i" == *"Trivia_"* ]] && [[ "$i" == *".mov"* ]]); then
        dontCopy="TRUE"
    else
        cp -p "$i" "$motionPath"
    fi
done