#!/bin/bash

uploadsPath="$1"
filePrefix="$3"
lookName="$4"
projName="$5"

for i in *.psd *.zip; do
    if [[ "$oneLook" == "FALSE" ]]; then 
        stillPath="${uploadsPath}${projName}_UPLOADS/${lookName}/Images/${filePrefix}_$i"
        motionPath="${uploadsPath}${projName}_UPLOADS/${lookName}/Motions/${filePrefix}_$i"
    elif [[ "$oneLook" == "TRUE" ]]; then
        stillPath="${uploadsPath}${projName}_UPLOADS/Images/${filePrefix}_$i"
        motionPath="${uploadsPath}${projName}_UPLOADS/Motions/${filePrefix}_$i"
    fi

    if [[ "$i" == *".psd"* ]]; then
        cp -p "$i" "$stillPath"
    elif [[ "$i" == *".zip"* ]]; then
        mv -p "$i" "$motionPath"
    fi
done