#!/bin/bash

uploadsPath="$1"
projName="$2"
lookName="$3"
sortError=()

#sorting identifiers
    collectionHero="HERO"
    collectionThumb="THUMB"

    socialLS="_LS"
    socialPR="_PR"
    socialSQ="_SQ"

    stillWIDE="_WIDE"
    stillSTD="_STD"
    stillPP="PP_"
    stillTitle1="TT1_"
    stillTitle2="TT2_"
    stillTitle3="TT3_"
    stillAlt1="ALT1_"
    stillAlt2="ALT2_"
    stillL3="L3_"
    stillL3Thumb="_TH_"
    stillDemo="DEMO_"
    stillDemoPSD="_PSD"
    stillDemoSocial="_SOC"
    stillSocial="SOC_"
    stillSocialS="_S_"
    stillSocialB="_B_"
    stillSocialOR="_OR"

    motionHD="_HD"
    motionSD="_SD"
    motionCD="Countdown_"
    motionTV="Trivia_"
    motionWB="WB_"
    motionUW="UW_"
    motionBP="BMP_"
    motionSocial="SOC_"
#

#preset tags
    presetAE="#preset=aep_zip"
    
    presetPPWide="#preset=ppt_wide"
    presetPPStandard="#preset=ppt_standard"
    presetTitle1="#preset=tg_title1"
    presetTitle2="#preset=tg_title2"
    presetTitle3="#preset=tg_title3"
    presetAlt1="#preset=tg_alt1"
    presetAlt2="#preset=tg_alt2"
    presetL3WIDE="#preset=tg_transparent_png_download_wide"
    presetL3STD="#preset=tg_transparent_png_download_standard"
    presetL3TH="#preset=tg_transparent_png_preview"
    presetSOCLS1="#preset=social_landscape1"
    presetSOCLS2="#preset=social_landscape2"
    presetSOCPR1="#preset=social_portrait1"
    presetSOCPR2="#preset=social_portrait2"
    presetSOCSQ1="#preset=social_square1"
    presetSOCSQ2="#preset=social_square2"
    presetSOCOR="#preset=social_orientations"
    presetHero="#preset=collection_hero"
    presetThumb="#preset=collection_thumbnail"
    presetDemoPSD="#preset=tg_psd_demo"
    presetDemoSOC="#preset=social_psd_demo"
#

# copy stills
cd "./STILL DELIVERABLES/"
for i in *; do
    stillPath="${uploadsPath}${projName}_MASTER/${lookName}/MOTIONS/${projName}_${lookName}_${i}"
    if [[ "$i" != *"*"* ]]; then
        if [[ "$i" == *"$stillPP"* ]]; then
            if [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetPPWIDE"
            elif [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetPPSTD"
            fi
        else
            if [[ "$i" == *"$stillTitle1"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle1"
            elif [[ "$i" == *"$stillTitle1"* ]] && [[ "$i" == *"$stillSTD"* ]]; then    
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle1"
            elif [[ "$i" == *"$stillTitle2"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle2"
            elif [[ "$i" == *"$stillTitle2"* ]] && [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle2"
            elif [[ "$i" == *"$stillTitle3"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle3"
            elif [[ "$i" == *"$stillTitle3"* ]] && [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetTitle3"
            elif [[ "$i" == *"$stillAlt1"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetAlt1"
            elif [[ "$i" == *"$stillAlt1"* ]] && [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetAlt1"
            elif [[ "$i" == *"$stillAlt2"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetAlt2"
            elif [[ "$i" == *"$stillAlt2"* ]] && [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetAlt2"
            elif [[ "$i" == *"$stillL3"* ]] && [[ "$i" == *"$stillWIDE"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetL3WIDE"
            elif [[ "$i" == *"$stillL3"* ]] && [[ "$i" == *"$stillSTD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetL3STD"
            elif [[ "$i" == *"$stillL3"* ]] && [[ "$i" == *"$stillWIDE"* ]] && [[ "$i" == *"$stillL3Thumb"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetL3TH"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialS" ]] && [[ "$i" == "$socialLS" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCLS1"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialS" ]] && [[ "$i" == "$socialPR" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCPR1"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialS" ]] && [[ "$i" == "$socialSQ" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCSQ1"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialB" ]] && [[ "$i" == "$socialLS" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCLS2"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialB" ]] && [[ "$i" == "$socialPR" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCPR2"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialB" ]] && [[ "$i" == "$socialSQ" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCSQ2"
            elif [[ "$i" == *"$stillSocial"* ]] && [[ "$i" == "$stillSocialOR" ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetSOCOR"
            elif [[ "$i" == *"$collectionHero"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetHero"
            elif [[ "$i" == *"$collectionThumb"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetThumb"
            elif [[ "$i" == *"$stillDemo"* ]] && [[ "$i" == *"$stillDemoPSD"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetDemoPSD]"
            elif [[ "$i" == *"$stillDemo"* ]] && [[ "$i" == *"$stillDemoSocial"* ]]; then
                echo "  $i"
                cp "$i" "${stillPath}$presetDemoSOC"
            else
                sortError+=("$i")
            fi
        fi
    fi
done
cd ..

# copy motions
cd "./MOTION DELIVERABLES/"
for i in *; do
    motionPath="${uploadsPath}${projName}_MASTER/${lookName}/MOTIONS/${projName}_${lookName}_ANIM_${i}"
    if [[ "$i" != *"*"* ]]; then
        if [[ -d "$i" ]]; then
            echo "  $i"
            zip -r "$i" . -i "$motionPath"
        else
            if [[ "$i" == *"$motionCD"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                ffmpeg -loglevel quiet -y -i "$i" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$motionPath" 
            elif [[ "$i" == *"$motionCD"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                ffmpeg -loglevel quiet -y -i "$i" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$motionPath" 
            elif [[ "$i" == *"$motionTV"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                ffmpeg -loglevel quiet -y -i "$i" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$motionPath" 
            elif [[ "$i" == *"$motionTV"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                ffmpeg -loglevel quiet -y -i "$i" -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 3M -minrate 3M -maxrate 3M -bufsize 5M -c:a aac -b:a 192k -pix_fmt yuv420p "$motionPath" 
            elif [[ "$i" == *"$motionWB"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionWB"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionUW"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionUW"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionBP"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionBP"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialLS"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialPR"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialSQ"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionHD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            elif [[ "$i" == *"$motionSD"* ]]; then
                echo "  $i"
                cp "$i" "$motionPath"
            else
                sortError+=("$i")
            fi
        fi
    fi
done
cd ..

#print errors
    if [[ "${#sortError[@]}" != 0 ]]; then
        echo
        echo "Could not copy these Files:"
        for t in "${sortError[@]}"; do
            echo "      $t"
        done
    fi
#