#!/bin/bash

textFilter="$1"

#quicktime madness
get_Thumb_Time() {

TIME=$(osascript <<-EOF
tell application "QuickTime Player"
		activate
		set thumbnailTime to current time of document 1
		close document 1
end tell
get thumbnailTime
EOF
    )
}
#

files=(*)
open "${files[0]}"
read -p "Press enter after choosing the thumbnail frame." answer
get_Thumb_Time $i

for i in *.mov; do
    if [[ "$i" == *"$textFilter"* ]] && [[ "$i" != "*.mov" ]]; then
        pngthumb=${i/mov}png
        jpgthumb=${i/mov}jpg

        echo "      Generating Thumb for $i from time $TIME"
        ffmpeg -loglevel quiet -y -ss $TIME -i "$i" -q:v 1 -vframes 1 "$pngthumb"
        sleep .5
        magick -quiet "$pngthumb" "$jpgthumb"
        sleep .5
        rm "$pngthumb"
        sleep .5
    fi
done