#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
sudo apt-get install build-essential
sudo apt-get update
sudo apt-get upgrade
brew install gcc
brew install ffmpeg
brew install imagemagick
brew upgrade
brew update

# alias reference for windows
alias addAlias="sudo nano .bashrc"
alias oneDir="find . -mindepth 2 -type f -print -exec mv {} . \;"
alias test="/mnt/c/Users/jere.baker/Documents/GitHub/test"
alias sdcrop="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/sdcrop"
alias workingFolders="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/workingFolders"
alias batchRename="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/batchRename"
alias uploads="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/uploads"
alias checkImages="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/checkImages"
alias checkMotions="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/checkMotions"
alias generateThumbs="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/generateThumbs"
alias compressMOV="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/compressMOV"
alias compressFolder="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/compressFolder"
alias processFilenames="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/processFilenames"
alias processPresets="/mnt/c/Users/jere.baker/Documents/GitHub/IG_Scripts/processPresets"