#!/bin/bash

ttFrame=$1
bgFrame=$2
uwFrame=$3
cdFrame=$4
tvFrame=$5
bpFrame=$6
scFrame=$7

#sorting identifiers
    collectionHero="HERO"
    collectionThumb="THUMB"

    socialLS="_LS"
    socialPR="_PR"
    socialSQ="_SQ"

    stillWIDE="_WIDE"
    stillSTD="_STD"
    stillPP="PP_"
    stillTitle1="TT1_"
    stillTitle2="TT2_"
    stillTitle3="TT3_"
    stillAlt1="ALT1_"
    stillAlt2="ALT2_"
    stillL3="L3_"
    stillL3Thumb="_TH_"
    stillDemo="DEMO_"
    stillDemoPSD="_PSD"
    stillDemoSocial="_SOC"
    stillSocial="SOC_"
    stillSocialS="_S_"
    stillSocialB="_B_"
    stillSocialOR="_OR"

    motionHD="_HD"
    motionSD="_SD"
    motionCD="Countdown_"
    motionTV="Trivia_"
    motionWB="WB_"
    motionUW="UW_"
    motionBP="BMP_"
    motionSocial="SOC_"
#

# generate thumbnails
cd "./MOTIONS/"
for i in *; do
    if [[ "$i" != *"*"* ]]; then
        if [[ -d "$i" ]]; then
			echo
			# check zip size
        else
            if [[ "$i" == *"$motionCD"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$cdFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionCD"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$cdFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionTV"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$tvFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionTV"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$tvFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionWB"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$bgFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionWB"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$bgFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionUW"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$uwFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionUW"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$uwFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionBP"* ]] && [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$bpFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionBP"* ]] && [[ "$i" == *"$motionSD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$bpFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialLS"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$scFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialPR"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$scFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionSocial"* ]] && [[ "$i" == *"$socialSQ"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$scFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionHD"* ]]; then
                thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$ttFrame)" -vframes 1 "$thumb"
            elif [[ "$i" == *"$motionSD"* ]]; then
				thumb=${i/mov}jpg
				echo "  $thumb"
                ffmpeg -loglevel quiet -y -i "$i" -q:v 1 -vf "select=eq(n\,$ttFrame)" -vframes 1 "$thumb"
            else
                sortError+=("$i")
            fi
        fi
    fi
done
cd ..

#print errors
    if [[ "${#sortError[@]}" != 0 ]]; then
        echo
        echo "Could not create thumbnails for these Files:"
        for t in "${sortError[@]}"; do
            echo "      $t"
        done
    fi
#