#!/bin/bash

scriptPath="$1"
filePrefix="$2"
uploadsPath="$3"
oneLook="$4"
lookName="$5"
projName="$6"

echo "Enter Frame Number for Thumbnails (leave blank if none)"
read -p "Titles:               " ttFrame
read -p "Worship Backgrounds:  " wbFrame
read -p "Ultra-Wides:          " uwFrame
read -p "Countdowns:           " cdFrame
read -p "Trivia:               " tvFrame
read -p "Bumpers:              " bpFrame
echo

echo "Processing Files for $filePrefix"
if [[ "$oneLook" == "FALSE" ]]; then 
    newImagesPath="${uploadsPath}${projName}_UPLOADS/${lookName}/Images/"
    newMotionsPath="${uploadsPath}${projName}_UPLOADS/${lookName}/Motions/"
elif [[ "$oneLook" == "TRUE" ]]; then
    newImagesPath="${uploadsPath}${projName}_UPLOADS/Images/"
    newMotionsPath="${uploadsPath}${projName}_UPLOADS/Motions/"
fi

cd "./02_Title"
for i in *; do
    cd "./$i/_Images"
    bash ${scriptPath}copyImages "$newImagesPath" "$filePrefix"
    cd ..
    cd "./_Motions"
    bash ${scriptPath}generateThumbs $ttFrame "_HD"
    bash ${scriptPath}copyMotions "$newMotionsPath" "$filePrefix"
    cd ..
    bash ${scriptPath}compressAE
    bash ${scriptPath}copyProjects "$newImagesPath" "$filePrefix"
    cd ..
done
cd ..

cd "./03_Social"
for i in *; do
    cd "./$i/_Images"
    bash ${scriptPath}copyImages "$newImagesPath" "$filePrefix"
    cd ..
    cd "./_Motions"
    bash ${scriptPath}copyMotions "$newMotionsPath" "$filePrefix"
    cd ../../
done
cd ..

cd "./04_Worship Background/_Motions"
bash ${scriptPath}generateThumbs $wbFrame "WB_" "_HD"
bash ${scriptPath}generateThumbs $uwFrame "UW_" "_SD"
bash ${scriptPath}copyMotions "$newMotionsPath" "$filePrefix"
cd ../../

cd "./05_Countdown & Trivia/_Motions"
bash ${scriptPath}generateThumbs $cdFrame "Countdown_" "_HD"
bash ${scriptPath}generateThumbs $tvFrame "Trivia_" "_HD"
bash ${scriptPath}compressCD
bash ${scriptPath}copyMotions "$newMotionsPath" "$filePrefix"
cd ../../

cd "./06_Bumper/_Motions"
bash ${scriptPath}generateThumbs $bpFrame "Bumper_" "_HD"
bash ${scriptPath}copyMotions "$newMotionsPath" "$filePrefix"
cd ../../