#!/bin/bash

scriptPath="$1"
filePrefix="$2"

echo "Processing Files for $filePrefix"
read -p "  Do you want to re-generate thumbnails for motions? (y/n)" thumbs
echo "  Removing Empty Folders"
mkdir -p "./00_Assets/_emptyFolders"
touch ./00_Assets/_emptyFolders/.hidden
find . -type d -empty -exec mv {} ./00_Assets/_emptyFolders/ &>/dev/null \;

if [[ -d "./02_Title" ]]; then
    echo "  Processing Titles"
    cd "./02_Title"
    for i in *; do
        if [[ -d "./$i" ]]; then
            cd "./$i"
            bash ${scriptPath}compressFolder "_AE"
            if [[ -d "./_Images" ]]; then
                echo "    Processing Stills for $i"
                cd "./_Images"
                bash ${scriptPath}processFilenames "$filePrefix"
                bash ${scriptPath}processPresets
                cd ..
            fi
            if [[ -d "./_Motions" ]]; then
                echo "    Processing Motions for $i"
                cd "./_Motions"
                if [[ "$thumbs" == "y" ]]; then 
                    bash ${scriptPath}generateThumbs "_HD" 
                fi
                bash ${scriptPath}compressMOV
                bash ${scriptPath}processFilenames "$filePrefix"
                bash ${scriptPath}processPresets
                cd ..
            fi
            cd ..
        fi
    done
    cd ..
fi

if [[ -d "./03_Social" ]]; then
    echo "  Processing Socials"
    cd "./03_Social"
    bash ${scriptPath}renameSocials
    for i in *; do
        cd "./$i"
        bash ${scriptPath}compressFolder "_AE"
        if [[ -d "./_Images" ]]; then
            echo "    Processing Stills for $i"
            cd "./_Images"
            bash ${scriptPath}processFilenames "$filePrefix"
            bash ${scriptPath}processPresets
            cd ..
        fi
        if [[ -d "./_Motions" ]]; then
            echo "    Processing Motions"
            cd "./_Motions"
            if [[ "$thumbs" == "y" ]]; then 
                bash ${scriptPath}generateThumbs "_SQ"
            fi
            bash ${scriptPath}compressMOV "_CH_"
            bash ${scriptPath}processFilenames "$filePrefix"
            bash ${scriptPath}processPresets
            cd ..
        fi
        cd ..
    done
    cd ..
fi

if [[ -d "./04_Worship Background/_Motions" ]]; then
    echo "  Processing Worship Backgrounds"
    cd "./04_Worship Background/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./05_Ultra Wide/_Motions" ]]; then
    echo "  Processing Ultra Wides"
    cd "./05_Ultra Wide/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./06_Countdown/_Motions" ]]; then
    echo "  Processing Countdowns"
    cd "./06_Countdown/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_HD" 
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./07_Trivia/_Motions" ]]; then
    echo "  Processing Trivia"
    cd "./07_Trivia/_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_HD" 
    fi
    bash ${scriptPath}compressMOV
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

if [[ -d "./08_Bumper" ]]; then
    echo "  Processing Bumper"
    cd "./08_Bumper"
    bash ${scriptPath}compressFolder "_AE"
    cd "./_Motions"
    if [[ "$thumbs" == "y" ]]; then 
        bash ${scriptPath}generateThumbs "_HD" 
    fi
    bash ${scriptPath}compressMOV    
    bash ${scriptPath}processFilenames "$filePrefix"
    bash ${scriptPath}processPresets
    cd ../../
fi

echo
echo "Finished Processing Files for $filePrefix"
echo
