#!/bin/bash

mkdir -p "Ultra-Wides"
mkdir -p "Worship Backgrounds"

for i in *.mov *.jpg *.png; do 
    if [[ "$i" == *"_UW_"* ]]; then
        mv "$i" "./Ultra-Wides/$i"
    elif [[ "$i" == *"_WB_"* ]]; then
        mv "$i" "./Worship Backgrounds/$i"
    fi
done