#!/bin/bash

OS=$(uname)

if [[ $OS == "Darwin" ]]; then
    workingPath="/Volumes/Storage Consolidation/Design Primary/_PRODUCTS/_Working/"
elif [[ $OS == "Linux" ]]; then
    workingPath="/mnt/q/Design Primary/_PRODUCTS/_Working/"
else
    echo "Not able to detect Operating System"
    exit
fi

#make folder structure in "_Working"
read -p "What is the name of this Project?  " pName
read -p "What are the look variations for this project? (separated by comma, leave blank if none)    " looksTemp
read -p "What are the main title names? (separated by comma, match order of looks)    " titleTemp
read -p "What are the type of social? (separated by comma, no spaces)    " socialTemp

IFS=',' read -ra looksArray <<< "$looksTemp"
IFS=',' read -ra titleTypes <<< "$titleTemp"
IFS=',' read -ra socialTypes <<< "$socialTemp"

makeFolders () {
    mkdir -p "01_Marketing"
    mkdir -p "01_Marketing/_Images"

    mkdir -p "02_Title"
    mkdir -p "02_Title/$1"
    mkdir -p "02_Title/$1/_Images"
    mkdir -p "02_Title/$1/_Motions"
    mkdir -p "02_Title/$1/_PowerPoints"
    mkdir -p "02_Title/Goodbye"
    mkdir -p "02_Title/Goodbye/_Images"
    mkdir -p "02_Title/Goodbye/_Motions"
    mkdir -p "02_Title/Goodbye/_PowerPoints"
    mkdir -p "02_Title/Events"
    mkdir -p "02_Title/Events/_Images"
    mkdir -p "02_Title/Events/_Motions"
    mkdir -p "02_Title/Events/_PowerPoints"
    mkdir -p "02_Title/Offering"
    mkdir -p "02_Title/Offering/_Images"
    mkdir -p "02_Title/Offering/_Motions"
    mkdir -p "02_Title/Offering/_PowerPoints"
    mkdir -p "02_Title/Welcome"
    mkdir -p "02_Title/Welcome/_Images"
    mkdir -p "02_Title/Welcome/_Motions"
    mkdir -p "02_Title/Welcome/_PowerPoints"

    mkdir -p "04_Worship Background"
    mkdir -p "04_Worship Background/_Motions"

    mkdir -p "05_Countdown & Trivia"
    mkdir -p "05_Countdown & Trivia/_Motions"

    mkdir -p "06_Bumper"
    mkdir -p "06_Bumper/_Images"
}

socialFolders () {
    mkdir -p "03_Social"
    mkdir -p "03_Social/$1"
    mkdir -p "03_Social/$1/_Images"
    mkdir -p "03_Social/$1/_Motions"
}

cd "$workingPath"
mkdir -p "${pName}_MASTER"
cd "./${pName}_MASTER"

if (( ${#looksArray[@]} > 1 )); then
    for i in ${!looksArray[@]}; do
        mkdir -p "${looksArray[$i]}"
        cd "./${looksArray[$i]}"
        makeFolders "${titleTypes[$i]}"
        for t in ${!socialTypes[@]}; do
            socialFolders "${socialTypes[$t]}"
        done
        cd ..
    done
else
    makeFolders "$titleTypes"
    for t in ${!socialTypes[@]}; do
        socialFolders "${socialTypes[$t]}"
    done
fi

mkdir -p "00_Assets"
mkdir -p "00_Project Cache"